-- Seed the current shared application configuration without copying users or hibah records.

INSERT INTO db_field (id, field_label, field_key, field_type, field_options, field_placeholder, field_description, is_required, display_order, is_active) VALUES
('f1790827481989', 'Tahun Anggaran', 'tahun_anggaran', 'list', '2020;2021;2022;2023;2024;2025;2026;2027;2028;2029;2030', '', '', 1, 0, 1),
('f1790827538328', 'Kode Rekening', 'kode_rekening', 'text', '', '', '', 1, 1, 1),
('f5', 'Pagu Anggaran (Rp)', 'anggaran', 'currency', '', '', '', 1, 2, 1),
('f1790827872895', 'Pokja Pengampu', 'pokja', 'list', 'Pokja Produksi;Pokja Bibit;Pokja Pakan', '', '', 1, 3, 1),
('f1790827913951', 'batas1', 'batas1', 'separator', '', '', '', 0, 4, 1),
('f1', 'Nama kelompok penerima', 'nama_kelompok', 'text', '', '', '', 1, 5, 1),
('f1790828394013', 'Kabupaten/Kota', 'kabkot', 'list', 'BANJARNEGARA;BANYUMAS;BATANG;BLORA;BOYOLALI;BREBES;CILACAP;DEMAK;GROBOGAN;JEPARA;KARANGANYAR;KEBUMEN;KENDAL;KLATEN;KOTA MAGELANG;KOTA PEKALONGAN;KOTA SEMARANG;KOTA TEGAL;KUDUS;MAGELANG;PATI;PEKALONGAN;PEMALANG;PURBALINGGA;PURWOREJO;REMBANG;SALATIGA;SEMARANG;SRAGEN;SUKOHARJO;SURAKARTA;TEGAL;TEMANGGUNG;WONOGIRI;WONOSOBO', '', '', 1, 6, 1),
('f1790828435045', 'Kecamatan', 'kecamatan', 'text', '', '', '', 1, 7, 1),
('f1790828463901', 'Desa/Kelurahan', 'desa', 'text', '', '', '', 1, 8, 1),
('f1790828630094', 'Alamat', 'alamat', 'paragraph', '', 'Tuliskan alamat sampai RT/RW', 'Contoh: Jalan Jenderal Gatos Subroto Komplek Tarubudaya RT.001/RW.002', 1, 9, 1),
('f2', 'Komoditas ternak', 'komoditas_ternak', 'checklist', 'Sapi Potong;Sapi Perah;Kerbau;Kambing Potong;Kambing Perah;Domba;Ayam Buras;Ayam Ras Pedaging;Ayam Ras Petelur;Itik Pedaging;Itik Petelur;Kalkun;Kelinci;Babi;Kuda', '', '', 1, 10, 1),
('f1790835242798', 'Populasi', 'populasi', 'text', 'Sapi Potong;Sapi Perah;Kerbau;Kambing Potong;Kambing Perah;Domba;Ayam Buras;Ayam Ras Pedaging;Ayam Ras Petelur;Itik Pedaging;Itik Petelur;Kalkun;Kelinci;Babi;Kuda', '', '', 0, 11, 1),
('f1790828855956', 'batas2', 'batas2', 'separator', '', '', '', 0, 12, 1),
('f1790834610793', 'Pengurus Kelompok', 'pengurus', 'header', '', '', '', 0, 13, 1),
('f1790834657591', 'Ketua', 'ketua', 'text', '', '', '', 1, 14, 1),
('f1790834961259', 'No HP (Ketua)', 'no_ketua', 'number', '', '08xxxxxxxxxx', '', 0, 15, 1),
('f1790863982764', 'NIK/KTP (Ketua)', 'ktp_ketua', 'text', '', '31xxxxxxxxxxxxxx', '', 0, 16, 1),
('f1790864737344', 'batas3', 'batas3', 'separator', '', '', '', 0, 17, 1),
('f1790835028014', 'Sekretaris', 'sekretaris', 'text', '', '', '', 1, 18, 1),
('f1790835059277', 'No HP (Sekretaris)', 'no_sekretaris', 'number', '', '08xxxxxxxxxx', '', 0, 19, 1),
('f1790864614499', 'NIK/KTP (Sekretaris)', 'ktp_sekretaris', 'text', '', '31xxxxxxxxxxxxxx', '', 0, 20, 1),
('f1790864759997', 'batas4', 'batas4', 'separator', '', '', '', 0, 21, 1),
('f1790835149829', 'Bendahara', 'bendahara', 'text', '', '', '', 1, 22, 1),
('f1790835175405', 'No HP (Bendahara)', 'no_bendahara', 'number', '', '08xxxxxxxxxx', '', 0, 23, 1),
('f1790864583610', 'NIK/KTP (Bendahara)', 'ktp_bendahara', 'text', '', '31xxxxxxxxxxxxxx', '', 0, 24, 1),
('f1790873341447', 'batas5', 'batas5', 'separator', '', '', '', 0, 25, 1),
('f1790873416918', 'NPHD (untuk yang lolos)', 'head_nphd', 'header', '', '', '', 0, 26, 1),
('f1790873450123', 'No SK', 'no_sk', 'text', '', '', '', 0, 27, 1),
('f1790873479143', 'Tanggal SK', 'tgl_sk', 'date', '', '', '', 0, 28, 1),
('f1790873492783', 'batas6', 'batas6', 'separator', '', '', '', 0, 29, 1),
('f1790873549281', 'Nomor NPHD', 'no_nphd', 'text', '', '', '', 0, 30, 1),
('f1790873572230', 'Tanggal NPHD', 'tgl_nphd', 'date', '', '', '', 0, 31, 1)
ON DUPLICATE KEY UPDATE field_label = VALUES(field_label), field_key = VALUES(field_key), field_type = VALUES(field_type), field_options = VALUES(field_options), field_placeholder = VALUES(field_placeholder), field_description = VALUES(field_description), is_required = VALUES(is_required), display_order = VALUES(display_order), is_active = VALUES(is_active);

INSERT INTO db_verification_field (id, field_label, field_key, field_type, field_options, field_placeholder, field_description, is_required, display_order, is_active) VALUES
('vf1790865346047', 'batas (salinan)', 'batas_copy_2', 'separator', '', '', '', 0, 0, 1),
('vf_kesesuaian', '1a. Surat (keterangan terdaftar) pengesahan/penetapan dan Dinas Peternakan Kabupaten/Kota', 'f1a', 'list', 'Ada;Tidak ada', '', 'Bandingkan data pengajuan dengan dokumen pendukung.', 1, 1, 1),
('vf1790838619513', 'Keterangan 1a', 'ket_1a', 'paragraph', '', '', '', 0, 2, 1),
('vf1790838638049', '1b. Teregistrasi dalam aplikasi SIMLUHTAN;(ada printout aplikasi SIMLUHTAN yangmenunjukkan adanya Nomor Register /Nomor ID Kelompok dalam SIMLUHTAN)', 'f1b', 'list', 'Ada;Tidak ada', '', 'Bandingkan data pengajuan dengan dokumen pendukung.', 1, 3, 1),
('vf1790838679481', 'Keterangan 1b', 'ket_1b', 'paragraph', '', '', '', 0, 4, 1),
('vf1790838732040', '2. SK Pengukuhan Kelompok dari Kepala Desa atau Lurah', 'f2', 'list', 'Ada;Tidak ada', '', 'Bandingkan data pengajuan dengan dokumen pendukung.', 1, 5, 1),
('vf1790838833624', 'Keterangan 2', 'ket_2', 'paragraph', '', '', '', 0, 6, 1),
('vf1790839041551', '3. Surat keterangan domisili kelompok dari Lurah/Kepala Desa setempat mengetahui Camat (dilengkapi stempel basah)', 'f3', 'list', 'Ada;Tidak ada', '', 'Bandingkan data pengajuan dengan dokumen pendukung.', 1, 7, 1),
('vf1790839121800', 'Keterangan 3', 'ket_3', 'paragraph', '', '', '', 0, 8, 1),
('vf1790844542700', '4. Memiliki susunan kepengurusan kelompok yang jelas di daerah yang bersangkutan (identitas kelompok; pengurus dan anggota) yang diketahui oleh Kepala Desa atau Lurah + Fotokopi KTP seluruh pengurus dan anggota kelompok (jumlah anggota kelompok minimal 10 orang)', 'f4', 'list', 'Ada;Tidak ada', '', 'Bandingkan data pengajuan dengan dokumen pendukung.', 1, 9, 1),
('vf1790844588340', 'Keterangan 4', 'ket_4', 'paragraph', '', '', '', 0, 10, 1),
('vf1790845137068', '5a. ●Kesesuaian nama dan alamat kelompok; kesesuaian kop dan stempel kelompok dengan yang tercantum di DPA', 'f5a', 'list', 'Ada;Tidak ada', '', 'Bandingkan data pengajuan dengan dokumen pendukung.', 1, 11, 1),
('vf1790845186922', 'Keterangan 5a', 'ket_5a', 'paragraph', '', '', '', 0, 12, 1),
('vf1790845164859', '5b. ●Tanggal proposal sebelum tanggal penetapanKUAPPAS (20 November 2025)', 'f5b', 'list', 'Ada;Tidak ada', '', 'Bandingkan data pengajuan dengan dokumen pendukung.', 1, 13, 1),
('vf1790845223434', 'Keterangan 5b', 'ket_5b', 'paragraph', '', '', '', 0, 14, 1),
('vf1790845540430', '5c. ●Surat permohonan/pengantar dari kelompok yang mengetahui Kades; Camat dan Dinas Peternakan/ yang membidangi fungsi peternakan Kabupaten/Kota lokasi kelompok (dilengkapi stempel basah)', 'f5c', 'list', 'Ada;Tidak ada', '', 'Bandingkan data pengajuan dengan dokumen pendukung.', 1, 15, 1),
('vf1790845569960', 'Keterangan 5c', 'ket_5c', 'paragraph', '', '', '', 0, 16, 1),
('vf1790846339959', '5d. ●Maksud dan tujuan untuk permohonan hibah uang', 'f5d', 'list', 'Ada;Tidak ada', '', 'Bandingkan data pengajuan dengan dokumen pendukung.', 1, 17, 1),
('vf1790846355493', 'Keterangan 5d', 'ket_5d', 'paragraph', '', '', '', 0, 18, 1),
('vf1790846482620', '5e. ●Profil singkat kelompok', 'f5e', 'list', 'Ada;Tidak ada', '', 'Bandingkan data pengajuan dengan dokumen pendukung.', 1, 19, 1),
('vf1790846504428', 'Keterangan 5e', 'ket_5e', 'paragraph', '', '', '', 0, 20, 1),
('vf1790846570788', '5f. ●Usulan Rencana Anggaran Biaya (RAB) Nilai RAB di proposal minimal sama dengan alokasi Pagu Anggaran DPA T.A. 2026 (RAB selain untuk pembelian ternak maksimal 15% dari Pagu Anggaran)', 'f5f', 'list', 'Ada;Tidak ada', '', 'Bandingkan data pengajuan dengan dokumen pendukung.', 1, 21, 1),
('vf1790846597484', 'Keterangan 5f', 'ket_5f', 'paragraph', '', '', '', 0, 22, 1),
('vf1790846632368', '5g. ●RAB di proposal :', 'ket_5g', 'number', '', '', '', 1, 23, 1),
('vf1790846685036', '5h. ●Pagu di DPA/DPPA :', 'ket_5h', 'number', '', '', '', 1, 24, 1),
('vf1790846725532', '5i. ●Bantuan yang pernah diterima dari Pemerintah (dalam bentuk apapun)', 'f5i', 'list', 'Ada;Tidak ada', '', 'Bandingkan data pengajuan dengan dokumen pendukung.', 1, 25, 1),
('vf1790846756220', 'Keterangan 5i', 'ket_5i', 'paragraph', '', '', '', 0, 26, 1),
('vf1790846795339', '5j. ●Sarana penunjang usaha peternakan (Foto lahan; kandang; potensi sumber pakan dan sarana produksi ternak lainnya)', 'f5j', 'list', 'Ada;Tidak ada', '', 'Bandingkan data pengajuan dengan dokumen pendukung.', 1, 27, 1),
('vf1790846813139', 'Keterangan 5j', 'ket_5j', 'paragraph', '', '', '', 0, 28, 1),
('vf1790846901772', 'batas', 'batas', 'separator', '', '', '', 0, 29, 1),
('vf1790846963715', 'Jenis bantuan yang diusulkan :', 'usulan_bantuan', 'paragraph', '', '', '', 0, 30, 1),
('vf1790847005019', 'Petugas Kabupaten/kota', 'nama_petugaskabkot', 'text', '', '', '', 0, 31, 1),
('vf1790847066347', 'batas (salinan)', 'batas_copy', 'separator', '', '', '', 0, 32, 1),
('vf1790847154123', 'Verifikator 1', 'verifikator1', 'list', '-;Athoillah, S.Pt, M.Pt;Aulia Vellarani, S.Si;Bangun Mustiko Arum, S.Si;Bella Faradia Pasha, S.Pt;Binta Rahmi, S. Pt, M.Si;Dr. Prasetyo Nugroho, S.Pt, M.Si;Drevian Meita Hardyastuti, S.Pt, M.Pt;drh. Anang Yusuf;drh. Arum Pamintaning Hermalis;drh. Diana Dwi Ariantie;drh. Edy Dharma, M.Sc;drh. Lim Chu Whi;drh. Purwoari Sulistiyo, M.Si;drh. Tri Wahyu Retnaningsih;Dwi Agustina Wijayanti, S.Pt;Dwi Kartika Palupi, S.P.;Dwi Retno Utami, S.Pt;Dwi Sutji Puspaningtyas, S.Pt;Eko Setiyawan, S.Pt;Eva Widowati, A.Md;Fatan Dwi Putra, S.Pt;Harini, S.St;Hatta Mardhika, S.TP;Ikhwan Kurnia Fauzi, S.TP;Ima Riyani;Ir. Diri Mulyatno, M.Si;Moh. Saekhu, S.ST;Nafi’ Nurul Nawwar Nida, S.Pt;Ni Putu Widiari, S.Pt, M.Si;Riswanto, S.Pt;Romaldus Dwi Fajar Nugroho, S.Pt;Rona Indra Cahya, S.Pt;Sukemi, S.ST;Sutrisno;Tita Mahargya Rosandari, S.Pt, MM;Umi Sholikhah, S.Pt;Vivid Bambang Sri Nugroho, S.Pt;Wahyuni, S.Si;Winda Ayu Harmayanti, S.Pt, M.Si;Wuri Handayani, S.Pt;Yoanne Apri Shendy, SE;Zan Baried Tirtana, S.KH', '', '', 0, 33, 1),
('vf1790847165706', 'Verifikator 2', 'verifikator2', 'list', '-;Athoillah, S.Pt, M.Pt;Aulia Vellarani, S.Si;Bangun Mustiko Arum, S.Si;Bella Faradia Pasha, S.Pt;Binta Rahmi, S. Pt, M.Si;Dr. Prasetyo Nugroho, S.Pt, M.Si;Drevian Meita Hardyastuti, S.Pt, M.Pt;drh. Anang Yusuf;drh. Arum Pamintaning Hermalis;drh. Diana Dwi Ariantie;drh. Edy Dharma, M.Sc;drh. Lim Chu Whi;drh. Purwoari Sulistiyo, M.Si;drh. Tri Wahyu Retnaningsih;Dwi Agustina Wijayanti, S.Pt;Dwi Kartika Palupi, S.P.;Dwi Retno Utami, S.Pt;Dwi Sutji Puspaningtyas, S.Pt;Eko Setiyawan, S.Pt;Eva Widowati, A.Md;Fatan Dwi Putra, S.Pt;Harini, S.St;Hatta Mardhika, S.TP;Ikhwan Kurnia Fauzi, S.TP;Ima Riyani;Ir. Diri Mulyatno, M.Si;Moh. Saekhu, S.ST;Nafi’ Nurul Nawwar Nida, S.Pt;Ni Putu Widiari, S.Pt, M.Si;Riswanto, S.Pt;Romaldus Dwi Fajar Nugroho, S.Pt;Rona Indra Cahya, S.Pt;Sukemi, S.ST;Sutrisno;Tita Mahargya Rosandari, S.Pt, MM;Umi Sholikhah, S.Pt;Vivid Bambang Sri Nugroho, S.Pt;Wahyuni, S.Si;Winda Ayu Harmayanti, S.Pt, M.Si;Wuri Handayani, S.Pt;Yoanne Apri Shendy, SE;Zan Baried Tirtana, S.KH', '', '', 0, 34, 1),
('vf1790847178002', 'Verifikator 3', 'verifikator3', 'list', '-;Athoillah, S.Pt, M.Pt;Aulia Vellarani, S.Si;Bangun Mustiko Arum, S.Si;Bella Faradia Pasha, S.Pt;Binta Rahmi, S. Pt, M.Si;Dr. Prasetyo Nugroho, S.Pt, M.Si;Drevian Meita Hardyastuti, S.Pt, M.Pt;drh. Anang Yusuf;drh. Arum Pamintaning Hermalis;drh. Diana Dwi Ariantie;drh. Edy Dharma, M.Sc;drh. Lim Chu Whi;drh. Purwoari Sulistiyo, M.Si;drh. Tri Wahyu Retnaningsih;Dwi Agustina Wijayanti, S.Pt;Dwi Kartika Palupi, S.P.;Dwi Retno Utami, S.Pt;Dwi Sutji Puspaningtyas, S.Pt;Eko Setiyawan, S.Pt;Eva Widowati, A.Md;Fatan Dwi Putra, S.Pt;Harini, S.St;Hatta Mardhika, S.TP;Ikhwan Kurnia Fauzi, S.TP;Ima Riyani;Ir. Diri Mulyatno, M.Si;Moh. Saekhu, S.ST;Nafi’ Nurul Nawwar Nida, S.Pt;Ni Putu Widiari, S.Pt, M.Si;Riswanto, S.Pt;Romaldus Dwi Fajar Nugroho, S.Pt;Rona Indra Cahya, S.Pt;Sukemi, S.ST;Sutrisno;Tita Mahargya Rosandari, S.Pt, MM;Umi Sholikhah, S.Pt;Vivid Bambang Sri Nugroho, S.Pt;Wahyuni, S.Si;Winda Ayu Harmayanti, S.Pt, M.Si;Wuri Handayani, S.Pt;Yoanne Apri Shendy, SE;Zan Baried Tirtana, S.KH', '', '', 0, 35, 1),
('vf1790847245642', 'Tanggal Verifikasi', 'tgl_verif', 'date', '', '', '', 0, 36, 1),
('vf1790847362690', 'Hasil Verifikasi', 'hasil_verif', 'list', '-;LOLOS;TIDAK LOLOS', '', '', 0, 37, 1),
('vf_catatan', 'Catatan verifikator', 'catatan_verifikator', 'paragraph', '', '', 'Tuliskan temuan atau tindak lanjut yang diperlukan.', 0, 38, 1),
('vf_dokumen', 'Kelengkapan dokumen', 'kelengkapan_dokumen', 'checklist', 'Surat Permohonan Kepada Gubernur;SKT;KTP;Proposal;Rencana Anggaran Biaya;Surat Pernyataan', '', 'Pilih seluruh dokumen yang sudah diterima dan diperiksa.', 0, 39, 1),
('vf1790847388882', 'batas3', 'batas3', 'separator', '', '', '', 0, 40, 1),
('vf1790847433667', 'FRAKSI', 'fraksi', 'list', '-;PDIP;PAN;GERINDRA;DEMOKRAT;NASDEM;PKS;PKB;PPP;GOLKAR', '', '', 0, 41, 1)
ON DUPLICATE KEY UPDATE field_label = VALUES(field_label), field_key = VALUES(field_key), field_type = VALUES(field_type), field_options = VALUES(field_options), field_placeholder = VALUES(field_placeholder), field_description = VALUES(field_description), is_required = VALUES(is_required), display_order = VALUES(display_order), is_active = VALUES(is_active);

INSERT INTO app_settings (setting_key, setting_value) VALUES
('announcement', CONCAT('Hibah dari pemerintah daerah adalah pemberian uang, barang, atau jasa yang bersumber dari Anggaran Pendapatan dan Belanja Daerah (APBD) kepada pihak lain yang bertujuan untuk menunjang penyelenggaraan urusan pemerintahan daerah.', CHAR(10), CHAR(10), 'Peraturan Gubernur Jawa Tengah Nomor 30 Tahun 2021 tentang Pedoman Pengelolaan Belanja Hibah Dan Bantuan Sosial Yang Bersumber Dari Anggaran Pendapatan Dan Belanja Daerah Provinsi Jawa Tengah')),
('announcement_style', '{"textColor":"#000000","backgroundColor":"#f4f4a4","fontSize":12,"speed":34,"transparency":0}'),
('library_items', '[{"id":"library-1791188366971-atgdt7","name":"Juknis Hibah Uang  Dinas Pertanian dan Peternakan Provinsi Jawa Tengah","documentNumber":"","documentDate":"","url":"https://drive.google.com/file/d/1m6LTKNI6051qAHvWgUwQvfU7z7Lnd9BW/view?usp=sharing"},{"id":"library-1791188922287-h8szv7","name":"Pergub 30 Tahun 2021","documentNumber":"No 30 Tahun 2021","documentDate":"2021-11-17","url":"https://peraturan.bpk.go.id/Read/186343/pergub_30_th_2021.pdf"}]')
ON DUPLICATE KEY UPDATE setting_value = VALUES(setting_value), updated_at = CURRENT_TIMESTAMP;

UPDATE app_metadata SET meta_value = '1' WHERE meta_key IN ('data_initialized', 'verification_fields_initialized');
